added download function

diff --git a/readm-dl b/readm-dl
--- a/readm-dl
+++ b/readm-dl
@@ -54,11 +54,53 @@ is_image() {
   return 0
 }
 
-main() {
+download() {
   local BASE_URL='https://www.readm.org/uploads/chapter_files'
+  local CHAPTER_NUM=1
+  local PAGE_NUM=1
+
+  local BOOK_NUM="${1}"
+
+  if [[ ! -e readmtmp ]]; then
+    echo "Download directory does not exist, run setup()."
+  fi
+
+  while true; do
+#     curl -s "${BASE_URL}/${CHAPTER_NUM}/${PAGE_NUM}.jpg" > readmtmp/${CHAPTER_NUM}-${PAGE_NUM}.jpg
+# 
+#     if ! is_image readmtmp/${CHAPTER_NUM}-${PAGE_NUM}.jpg;
+#       return 0
+#     fi
+    # Have to download all pages, incrementing PAGE_NUM each download.
+    # When is_image returns 1, increment CHAPTER_NUM, reset PAGE_NUM to 1, start download again.
+    # If is_image returns 1 AND PAGE_NUM = 1 then book is done.
+
+    # test if 1-1 can be dled
+    curl -s "${BASE_URL}/${CHAPTER_NUM}/${PAGE_NUM}.jpg" > readmtmp/${CHAPTER_NUM}-${PAGE_NUM}.jpg
+
+    if ! is_image readmtmp/1-1.jpg;
+      echo "Could not download first page. Does manga exist?"
+      return 0
+    fi
+    
+    # chapter loop
+    while true; do
+      # page loop
+      # 
+      #
+
+      CHAPTER_NUM=$((CHAPTER_NUM+1))
+    done
+  done
+  # assume all images are .jpg for now
+
+}
+
+main() {
   local BOOK_NUM="${1}"
   local CHAPTER_NUM="${2}"
 
+  # might not need setup
   setup $(num_to_title ${BOOK_NUM})
 
   curl -s "${BASE_URL}/${BOOK_NUM}/${CHAPTER_NUM}/1.jpg" > test.jpg
